apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app-servicemonitor
  labels:
    app: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  endpoints:
  - port: web
    path: /metrics
    interval: 1s
  namespaceSelector:
    matchNames:
    - default
