replicaCount: 1

image:
  repository: johnnytengu/demo-app
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  tls:
     secretName: "quickstart-example-tls"
  hosts:
    - host: demo.local
      paths:
        - path: /
          pathType: ImplementationSpecific
